/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author marcquizon
 */
public class MenuTechnicianFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuTechnicianFrame.class.getName());
    private static String displayIDnumber;//Used for the Welcome Label, static so that it does not change when switching frames

    /**
     * Creates new form MenuTechnicianFrame
     */
    public MenuTechnicianFrame() {
        initComponents();
        this.setResizable(false);
        technicianIDLabel.setText("ID#" + displayIDnumber);

    }

    public MenuTechnicianFrame(String idnumber) {
        initComponents();
        this.setResizable(false);
        displayIDnumber = idnumber; //Initiazes the displayIDnumber with the idnumber inputted in the LoginFrame
        technicianIDLabel.setText("ID#" + displayIDnumber);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        technicianBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        testerBtn = new javax.swing.JButton();
        machineBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        reportsBtn = new javax.swing.JButton();
        transac3Btn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        softwareBtn = new javax.swing.JButton();
        transac1Btn = new javax.swing.JButton();
        transac4Btn = new javax.swing.JButton();
        maintenanceBtn = new javax.swing.JButton();
        patchBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        technicianIDLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(40, 48, 143));
        jPanel1.setPreferredSize(new java.awt.Dimension(849, 599));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/SmallLogo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Andale Mono", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("TECHNICIAN MENU");

        technicianBtn.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        technicianBtn.setText("Technicians");
        technicianBtn.setMaximumSize(new java.awt.Dimension(85, 30));
        technicianBtn.setMinimumSize(new java.awt.Dimension(85, 30));
        technicianBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                technicianBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Record Management");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        testerBtn.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        testerBtn.setText("Testers");
        testerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testerBtnActionPerformed(evt);
            }
        });

        machineBtn.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        machineBtn.setText("Machines");
        machineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machineBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Transactions");

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));

        reportsBtn.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        reportsBtn.setText("Generate reports");
        reportsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsBtnActionPerformed(evt);
            }
        });

        transac3Btn.setFont(new java.awt.Font("Krungthep", 0, 17)); // NOI18N
        transac3Btn.setText("Schedule patch work to technician");
        transac3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transac3BtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(255, 255, 204));
        logoutBtn.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.setBorderPainted(false);
        logoutBtn.setOpaque(true);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        softwareBtn.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        softwareBtn.setText("Software");
        softwareBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                softwareBtnActionPerformed(evt);
            }
        });

        transac1Btn.setFont(new java.awt.Font("Krungthep", 0, 17)); // NOI18N
        transac1Btn.setText("Release new patch");
        transac1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transac1BtnActionPerformed(evt);
            }
        });

        transac4Btn.setFont(new java.awt.Font("Krungthep", 0, 17)); // NOI18N
        transac4Btn.setText("Update maintenance record");
        transac4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transac4BtnActionPerformed(evt);
            }
        });

        maintenanceBtn.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        maintenanceBtn.setText("Maintenance");
        maintenanceBtn.setMaximumSize(new java.awt.Dimension(85, 30));
        maintenanceBtn.setMinimumSize(new java.awt.Dimension(85, 30));
        maintenanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceBtnActionPerformed(evt);
            }
        });

        patchBtn.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        patchBtn.setText("Patch");
        patchBtn.setMaximumSize(new java.awt.Dimension(85, 30));
        patchBtn.setMinimumSize(new java.awt.Dimension(85, 30));
        patchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patchBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Welcome");

        technicianIDLabel.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        technicianIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        technicianIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(technicianIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logoutBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(testerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(patchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(maintenanceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(technicianBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(machineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(softwareBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 60, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(transac3Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transac1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(transac4Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                            .addComponent(reportsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(technicianBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(machineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(softwareBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maintenanceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transac3Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transac4Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transac1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(technicianIDLabel)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void technicianBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_technicianBtnActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == technicianBtn) {
            RecordsTechnicianFrame recordstechnician = new RecordsTechnicianFrame();
            recordstechnician.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_technicianBtnActionPerformed

    private void testerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testerBtnActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == testerBtn) {
            RecordsTesterFrame recordstester = new RecordsTesterFrame();
            recordstester.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_testerBtnActionPerformed

    private void machineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machineBtnActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == machineBtn) {
            RecordsMachineFrame recordsMachine = new RecordsMachineFrame();
            recordsMachine.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_machineBtnActionPerformed

    private void reportsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsBtnActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == reportsBtn) {
            ReportsFrame reportsFrame = new ReportsFrame();
            reportsFrame.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_reportsBtnActionPerformed

    private void transac3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transac3BtnActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == transac3Btn) {
            Transac3Frame transac3Frame = new Transac3Frame();
            transac3Frame.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_transac3BtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == logoutBtn) {
            int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Confirm logout", JOptionPane.YES_OPTION);

            if (result == JOptionPane.YES_OPTION) {
                System.out.println("Technician ID "+ displayIDnumber + " logged out");
                LoginFrame loginFrame = new LoginFrame();
                loginFrame.setVisible(true);
                this.dispose();
            } else if (result == JOptionPane.CLOSED_OPTION) {
                System.out.println("Technician ID " + displayIDnumber + " did not log out");
            }
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void softwareBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_softwareBtnActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == softwareBtn) {
            RecordsSoftwareFrame recordsSoftware = new RecordsSoftwareFrame();
            recordsSoftware.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_softwareBtnActionPerformed

    private void transac1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transac1BtnActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == transac1Btn) {
            Transac1Frame transac1Frame = new Transac1Frame();
            transac1Frame.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_transac1BtnActionPerformed

    private void transac4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transac4BtnActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == transac4Btn) {
            Transac4Frame transac4Frame = new Transac4Frame();
            transac4Frame.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_transac4BtnActionPerformed

    private void maintenanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceBtnActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == maintenanceBtn) {
            RecordsMaintenanceFrame recordsMaintenance = new RecordsMaintenanceFrame();
            recordsMaintenance.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_maintenanceBtnActionPerformed

    private void patchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patchBtnActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == patchBtn) {
            RecordsPatchFrame recordsPatch = new RecordsPatchFrame();
            recordsPatch.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_patchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuTechnicianFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton machineBtn;
    private javax.swing.JButton maintenanceBtn;
    private javax.swing.JButton patchBtn;
    private javax.swing.JButton reportsBtn;
    private javax.swing.JButton softwareBtn;
    private javax.swing.JButton technicianBtn;
    private javax.swing.JLabel technicianIDLabel;
    private javax.swing.JButton testerBtn;
    private javax.swing.JButton transac1Btn;
    private javax.swing.JButton transac3Btn;
    private javax.swing.JButton transac4Btn;
    // End of variables declaration//GEN-END:variables
}
