/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Machine;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author marcquizon
 */
public class RecordsMachineFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RecordsMachineFrame.class.getName());

    /**
     * Creates new form AdminMenuFrame
     */
    public RecordsMachineFrame() {
        initComponents();
        this.setResizable(false);
        addPanel.setVisible(false);
        editPanel.setVisible(false);
        deletePanel.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plainPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        addUsernameField1 = new javax.swing.JTextField();
        addPasswordField1 = new javax.swing.JTextField();
        addEmailField1 = new javax.swing.JTextField();
        addtesterBtn1 = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        resultsLbl = new javax.swing.JLabel();
        searchIDField = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        actionComboBox = new javax.swing.JComboBox<>();
        deletePanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        deleteMachineIDField = new javax.swing.JTextField();
        deleteMachineBtn = new javax.swing.JButton();
        addPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addMachineNameField = new javax.swing.JTextField();
        addMachineBtn = new javax.swing.JButton();
        addTypeComboBox = new javax.swing.JComboBox<>();
        editPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        editMachineNameField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        editTypeComboBox = new javax.swing.JComboBox<>();
        editConfirmBtn = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        editMachineIDField = new javax.swing.JTextField();
        editEnterBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        editStatusComboBox = new javax.swing.JComboBox<>();

        plainPanel.setBackground(new java.awt.Color(40, 48, 143));

        jLabel11.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Username:");

        jLabel12.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Password:");

        jLabel13.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Email:");

        addUsernameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUsernameField1ActionPerformed(evt);
            }
        });

        addPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPasswordField1ActionPerformed(evt);
            }
        });

        addEmailField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmailField1ActionPerformed(evt);
            }
        });

        addtesterBtn1.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        addtesterBtn1.setText("Add Tester");
        addtesterBtn1.setBorderPainted(false);
        addtesterBtn1.setOpaque(true);
        addtesterBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtesterBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plainPanelLayout = new javax.swing.GroupLayout(plainPanel);
        plainPanel.setLayout(plainPanelLayout);
        plainPanelLayout.setHorizontalGroup(
            plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plainPanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addUsernameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(plainPanelLayout.createSequentialGroup()
                        .addGroup(plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addEmailField1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(addtesterBtn1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        plainPanelLayout.setVerticalGroup(
            plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plainPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUsernameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(plainPanelLayout.createSequentialGroup()
                        .addGroup(plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addEmailField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(plainPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(addtesterBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(40, 48, 143));
        mainPanel.setPreferredSize(new java.awt.Dimension(849, 600));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/SmallLogo.png"))); // NOI18N
        mainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        jLabel2.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Machine Records");
        mainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 0, 199, 85));

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Select Action");
        mainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 338, 118, 28));

        backBtn.setBackground(new java.awt.Color(255, 255, 204));
        backBtn.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        backBtn.setText("back");
        backBtn.setBorderPainted(false);
        backBtn.setOpaque(true);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        mainPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 576, 105, 21));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 366, 838, 10));

        resultsLbl.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        resultsLbl.setForeground(new java.awt.Color(255, 255, 255));
        resultsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultsLbl.setText("Results found");
        mainPanel.add(resultsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 62, 178, 28));
        mainPanel.add(searchIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 31, 178, -1));

        SearchBtn.setFont(new java.awt.Font("Krungthep", 0, 14)); // NOI18N
        SearchBtn.setText("Search");
        SearchBtn.setBorderPainted(false);
        SearchBtn.setOpaque(true);
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        mainPanel.add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 31, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 96, 838, 236));

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Search ID:");
        mainPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 28, 88, 28));

        actionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add", "Edit", "Delete" }));
        actionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionComboBoxActionPerformed(evt);
            }
        });
        mainPanel.add(actionComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 338, 110, 26));

        deletePanel.setBackground(new java.awt.Color(40, 48, 143));

        jLabel14.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("MachineID:");

        deleteMachineIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMachineIDFieldActionPerformed(evt);
            }
        });

        deleteMachineBtn.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        deleteMachineBtn.setText("Delete Machine");
        deleteMachineBtn.setBorderPainted(false);
        deleteMachineBtn.setOpaque(true);
        deleteMachineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMachineBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deletePanelLayout = new javax.swing.GroupLayout(deletePanel);
        deletePanel.setLayout(deletePanelLayout);
        deletePanelLayout.setHorizontalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteMachineIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(deletePanelLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(deleteMachineBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deletePanelLayout.setVerticalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteMachineIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(deleteMachineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        mainPanel.add(deletePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 830, -1));

        addPanel.setBackground(new java.awt.Color(40, 48, 143));

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Machine Name:");

        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Type:");

        addMachineNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMachineNameFieldActionPerformed(evt);
            }
        });

        addMachineBtn.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        addMachineBtn.setText("Add Machine");
        addMachineBtn.setBorderPainted(false);
        addMachineBtn.setOpaque(true);
        addMachineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMachineBtnActionPerformed(evt);
            }
        });

        addTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PC", "Router", "Switch", "Server" }));

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addMachineNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(addTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(addMachineBtn)))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addMachineNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(addMachineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        mainPanel.add(addPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 838, -1));

        editPanel.setBackground(new java.awt.Color(40, 48, 143));

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Machine Name:");

        editMachineNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMachineNameFieldActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Type:");

        editTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PC", "Router", "Switch", "Server" }));

        editConfirmBtn.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        editConfirmBtn.setText("Confirm changes");
        editConfirmBtn.setBorderPainted(false);
        editConfirmBtn.setOpaque(true);
        editConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editConfirmBtnActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("MachineID:");

        editMachineIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMachineIDFieldActionPerformed(evt);
            }
        });

        editEnterBtn.setFont(new java.awt.Font("Krungthep", 0, 12)); // NOI18N
        editEnterBtn.setText("enter");
        editEnterBtn.setBorderPainted(false);
        editEnterBtn.setOpaque(true);
        editEnterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEnterBtnActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Status:");

        editStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Healthy", "Vulnerable" }));

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editMachineIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editEnterBtn))
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editPanelLayout.createSequentialGroup()
                                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editMachineNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(editPanelLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(editConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editMachineIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editEnterBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editMachineNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editConfirmBtn)
                        .addGap(52, 52, 52))))
        );

        mainPanel.add(editPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 830, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        MenuTechnicianFrame menuTechnician = new MenuTechnicianFrame();
        menuTechnician.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
        String machineID = searchIDField.getText().trim();

        if (machineID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter a Machine ID to search", "Search", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        try {
            Machine m = Machine.getInfo(machineID);

            if (m.getMachineID() == null || m.getMachineID().isBlank()) {
                resultsLbl.setText("0 results found");
                JOptionPane.showMessageDialog(this, "Machine ID not found", "Search", JOptionPane.INFORMATION_MESSAGE);
                // clear table
                jTable1.setModel(new DefaultTableModel(new Object[][]{}, new String[]{"Machine ID", "Machine Name", "Device Type", "Status"}));
            } else {
                resultsLbl.setText("1 result found");
                DefaultTableModel tbl = new DefaultTableModel(new String[]{"Machine ID", "Machine Name", "Device Type", "Status"}, 0);
                tbl.addRow(new Object[]{
                    m.getMachineID(),
                    m.getMachineName(),
                    m.getDeviceType(),
                    m.getStatus()
                });
                jTable1.setModel(tbl);
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Search error", ex);
            JOptionPane.showMessageDialog(this, "Error during search: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void actionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionComboBoxActionPerformed
        // TODO add your handling code here:
        String selectedAction = (String) actionComboBox.getSelectedItem();

        if ("Add".equals(selectedAction)) {
            addPanel.setVisible(true);
            editPanel.setVisible(false);
            deletePanel.setVisible(false);

        } else if ("Edit".equals(selectedAction)) {
            addPanel.setVisible(false);
            editPanel.setVisible(true);
            deletePanel.setVisible(false);

        } else {
            deletePanel.setVisible(true);
            addPanel.setVisible(false);
            editPanel.setVisible(false);
        }
        
        mainPanel.revalidate();
        mainPanel.repaint();

    }//GEN-LAST:event_actionComboBoxActionPerformed

    private void addMachineNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMachineNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMachineNameFieldActionPerformed

    private void addMachineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMachineBtnActionPerformed
        // TODO add your handling code here:
        String machineName = addMachineNameField.getText().trim();
        String type = (String) addTypeComboBox.getSelectedItem();
        // For add, status should default to Healthy per DB design. But model.add requires a status param.
        // We'll set default status "Healthy" (model enforces only Healthy/Vulnerable).
        String defaultStatus = "Healthy";

        if (machineName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Machine name is required.", "Add Machine", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String result = Machine.add(machineName, type, defaultStatus);

            switch (result) {
                case "Valid":
                    JOptionPane.showMessageDialog(this, "Machine added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    // clear input and optionally refresh table by searching for the added name not available, so just clear
                    addMachineNameField.setText("");
                    resultsLbl.setText("Machine added");
                    break;
                case "Empty":
                    JOptionPane.showMessageDialog(this, "Please fill all required fields.", "Error", JOptionPane.ERROR_MESSAGE);
                    break;
                case "Duplicate Name":
                    JOptionPane.showMessageDialog(this, "Machine name already exists.", "Error", JOptionPane.ERROR_MESSAGE);
                    break;
                case "Invalid Status":
                    JOptionPane.showMessageDialog(this, "Invalid status provided.", "Error", JOptionPane.ERROR_MESSAGE);
                    break;
                case "Invalid":
                    JOptionPane.showMessageDialog(this, "Database error while adding machine.", "Error", JOptionPane.ERROR_MESSAGE);
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Unknown response: " + result, "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Add error", ex);
            JOptionPane.showMessageDialog(this, "Error adding machine: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addMachineBtnActionPerformed

    private void addUsernameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUsernameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addUsernameField1ActionPerformed

    private void addPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPasswordField1ActionPerformed

    private void addEmailField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmailField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addEmailField1ActionPerformed

    private void addtesterBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtesterBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addtesterBtn1ActionPerformed

    private void deleteMachineIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMachineIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMachineIDFieldActionPerformed

    private void deleteMachineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMachineBtnActionPerformed
        // TODO add your handling code here:
        String machineID = deleteMachineIDField.getText().trim();

        if (machineID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Machine ID to delete.", "Delete", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete (set Inactive) machine " + machineID + "?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            String result = Machine.delete(machineID);

            switch (result) {
                case "Valid":
                    JOptionPane.showMessageDialog(this, "Machine deleted (set to Inactive).", "Deleted", JOptionPane.INFORMATION_MESSAGE);
                    deleteMachineIDField.setText("");
                    resultsLbl.setText("Machine deleted");
                    break;
                case "Empty":
                    JOptionPane.showMessageDialog(this, "Please enter Machine ID.", "Error", JOptionPane.ERROR_MESSAGE);
                    break;
                case "Missing":
                    JOptionPane.showMessageDialog(this, "Machine not found.", "Error", JOptionPane.ERROR_MESSAGE);
                    break;
                case "Blocked":
                    JOptionPane.showMessageDialog(this, "Machine has active maintenance records and cannot be deleted.", "Blocked", JOptionPane.ERROR_MESSAGE);
                    break;
                case "Invalid":
                    JOptionPane.showMessageDialog(this, "Database error while deleting machine.", "Error", JOptionPane.ERROR_MESSAGE);
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Unknown response: " + result, "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Delete error", ex);
            JOptionPane.showMessageDialog(this, "Error deleting machine: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteMachineBtnActionPerformed

    private void editMachineNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMachineNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editMachineNameFieldActionPerformed

    private void editConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editConfirmBtnActionPerformed
        // TODO add your handling code here:
        String machineID = editMachineIDField.getText().trim();
        String machineName = editMachineNameField.getText().trim();
        String deviceType = (String) editTypeComboBox.getSelectedItem();
        String status = (String) editStatusComboBox.getSelectedItem();

        if (machineID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Machine ID is required.", "Edit", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String result = Machine.edit(machineID, machineName, deviceType, status);

            switch (result) {
                case "Valid":
                    JOptionPane.showMessageDialog(this, "Machine updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                    resultsLbl.setText("Machine updated.");
                    break;
                case "Missing":
                    JOptionPane.showMessageDialog(this, "Machine not found.", "Error", JOptionPane.ERROR_MESSAGE);
                    break;
                case "Empty":
                    JOptionPane.showMessageDialog(this, "Required fields are empty.", "Error", JOptionPane.ERROR_MESSAGE);
                    break;
                case "Invalid Status":
                    JOptionPane.showMessageDialog(this, "Invalid status selected.", "Error", JOptionPane.ERROR_MESSAGE);
                    break;
                case "Duplicate Name":
                    JOptionPane.showMessageDialog(this, "Another machine with that name exists.", "Error", JOptionPane.ERROR_MESSAGE);
                    break;
                case "Invalid":
                    JOptionPane.showMessageDialog(this, "Database error while updating machine.", "Error", JOptionPane.ERROR_MESSAGE);
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Unknown response: " + result, "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Edit error", ex);
            JOptionPane.showMessageDialog(this, "Error updating machine: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editConfirmBtnActionPerformed

    private void editMachineIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMachineIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editMachineIDFieldActionPerformed

    private void editEnterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEnterBtnActionPerformed
        // TODO add your handling code here:
        String machineID = editMachineIDField.getText().trim();

        if (machineID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter Machine ID", "Edit", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Machine m = Machine.getInfo(machineID);

            if (m.getMachineID() == null || m.getMachineID().isBlank()) {
                JOptionPane.showMessageDialog(this, "Machine ID not found", "Edit", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // populate fields
            editMachineNameField.setText(m.getMachineName());
            editTypeComboBox.setSelectedItem(m.getDeviceType());
            // status may be null in DB; protect against that
            if (m.getStatus() != null && (m.getStatus().equals("Healthy") || m.getStatus().equals("Vulnerable"))) {
                editStatusComboBox.setSelectedItem(m.getStatus());
            } else {
                editStatusComboBox.setSelectedIndex(0);
            }
            resultsLbl.setText("Machine loaded for edit.");

        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Load machine error", ex);
            JOptionPane.showMessageDialog(this, "Error loading machine: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editEnterBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RecordsMachineFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchBtn;
    private javax.swing.JComboBox<String> actionComboBox;
    private javax.swing.JTextField addEmailField1;
    private javax.swing.JButton addMachineBtn;
    private javax.swing.JTextField addMachineNameField;
    private javax.swing.JPanel addPanel;
    private javax.swing.JTextField addPasswordField1;
    private javax.swing.JComboBox<String> addTypeComboBox;
    private javax.swing.JTextField addUsernameField1;
    private javax.swing.JButton addtesterBtn1;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteMachineBtn;
    private javax.swing.JTextField deleteMachineIDField;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JButton editConfirmBtn;
    private javax.swing.JButton editEnterBtn;
    private javax.swing.JTextField editMachineIDField;
    private javax.swing.JTextField editMachineNameField;
    private javax.swing.JPanel editPanel;
    private javax.swing.JComboBox<String> editStatusComboBox;
    private javax.swing.JComboBox<String> editTypeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel plainPanel;
    private javax.swing.JLabel resultsLbl;
    private javax.swing.JTextField searchIDField;
    // End of variables declaration//GEN-END:variables
}
