/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import Model.Patch;
import Model.Tester;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author marcquizon
 */
public class RecordsPatchFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RecordsPatchFrame.class.getName());

    /**
     * Creates new form AdminMenuFrame
     */
    public RecordsPatchFrame() {
        initComponents();
        this.setResizable(false);
        editPanel.setVisible(false);
        deletePanel.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plainPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        addUsernameField1 = new javax.swing.JTextField();
        addPasswordField1 = new javax.swing.JTextField();
        addEmailField1 = new javax.swing.JTextField();
        addtesterBtn1 = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        resultsLbl = new javax.swing.JLabel();
        searchIDField = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        actionComboBox = new javax.swing.JComboBox<>();
        deletePanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        deletePatchIDField = new javax.swing.JTextField();
        deletePatchBtn = new javax.swing.JButton();
        editPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        editPatchNameField = new javax.swing.JTextField();
        editSoftwareIDField = new javax.swing.JTextField();
        editConfirmBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        editMachineIDField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        editPatchIDField = new javax.swing.JTextField();
        editEnterBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        editTechnicianIDField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        editDescriptionField = new javax.swing.JTextField();
        patchStatusField = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        editPatchTypeComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ActivateBtn = new javax.swing.JButton();

        plainPanel.setBackground(new java.awt.Color(40, 48, 143));

        jLabel11.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Username:");

        jLabel12.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Password:");

        jLabel13.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Email:");

        addUsernameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUsernameField1ActionPerformed(evt);
            }
        });

        addPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPasswordField1ActionPerformed(evt);
            }
        });

        addEmailField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmailField1ActionPerformed(evt);
            }
        });

        addtesterBtn1.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        addtesterBtn1.setText("Add Tester");
        addtesterBtn1.setBorderPainted(false);
        addtesterBtn1.setOpaque(true);
        addtesterBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtesterBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plainPanelLayout = new javax.swing.GroupLayout(plainPanel);
        plainPanel.setLayout(plainPanelLayout);
        plainPanelLayout.setHorizontalGroup(
            plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plainPanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addUsernameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(plainPanelLayout.createSequentialGroup()
                        .addGroup(plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addEmailField1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(addtesterBtn1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        plainPanelLayout.setVerticalGroup(
            plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plainPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUsernameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(plainPanelLayout.createSequentialGroup()
                        .addGroup(plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addEmailField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(plainPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(addtesterBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(40, 48, 143));
        mainPanel.setPreferredSize(new java.awt.Dimension(849, 600));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/SmallLogo.png"))); // NOI18N
        mainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        jLabel2.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Patch Records");
        mainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 0, 199, 85));

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Click \"Release new Patch\" on Menu to add a Patch Record");
        mainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 430, 28));

        backBtn.setBackground(new java.awt.Color(255, 255, 204));
        backBtn.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        backBtn.setText("back");
        backBtn.setBorderPainted(false);
        backBtn.setOpaque(true);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        mainPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 576, 105, 21));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 366, 838, 10));

        resultsLbl.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        resultsLbl.setForeground(new java.awt.Color(255, 255, 255));
        resultsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultsLbl.setText("Results found");
        mainPanel.add(resultsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 62, 178, 28));
        mainPanel.add(searchIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 31, 178, -1));

        SearchBtn.setFont(new java.awt.Font("Krungthep", 0, 14)); // NOI18N
        SearchBtn.setText("Search");
        SearchBtn.setBorderPainted(false);
        SearchBtn.setOpaque(true);
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        mainPanel.add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 31, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 96, 838, 236));

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Search ID:");
        mainPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 28, 88, 28));

        actionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Edit", "Delete" }));
        actionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionComboBoxActionPerformed(evt);
            }
        });
        mainPanel.add(actionComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 338, 110, 26));

        deletePanel.setBackground(new java.awt.Color(40, 48, 143));

        jLabel14.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("PatchID:");

        deletePatchIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePatchIDFieldActionPerformed(evt);
            }
        });

        deletePatchBtn.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        deletePatchBtn.setText("Delete Patch");
        deletePatchBtn.setBorderPainted(false);
        deletePatchBtn.setOpaque(true);
        deletePatchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePatchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deletePanelLayout = new javax.swing.GroupLayout(deletePanel);
        deletePanel.setLayout(deletePanelLayout);
        deletePanelLayout.setHorizontalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deletePatchIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(deletePanelLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(deletePatchBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deletePanelLayout.setVerticalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletePatchIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(deletePatchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        mainPanel.add(deletePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 830, -1));

        editPanel.setBackground(new java.awt.Color(40, 48, 143));
        editPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Patch Name:");
        editPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 40, -1, 28));

        jLabel9.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Status:");
        editPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 28));

        jLabel10.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Type:");
        editPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 81, 72, 28));

        editPatchNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPatchNameFieldActionPerformed(evt);
            }
        });
        editPanel.add(editPatchNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 43, 171, -1));

        editSoftwareIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSoftwareIDFieldActionPerformed(evt);
            }
        });
        editPanel.add(editSoftwareIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 171, -1));

        editConfirmBtn.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        editConfirmBtn.setText("Confirm edits");
        editConfirmBtn.setBorderPainted(false);
        editConfirmBtn.setOpaque(true);
        editConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editConfirmBtnActionPerformed(evt);
            }
        });
        editPanel.add(editConfirmBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 6, -1, 158));

        jLabel15.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("MachineID:");
        editPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 40, 113, 28));

        editMachineIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMachineIDFieldActionPerformed(evt);
            }
        });
        editPanel.add(editMachineIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 43, 171, -1));

        jLabel16.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("PatchID");
        editPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 6, -1, 28));

        editPatchIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPatchIDFieldActionPerformed(evt);
            }
        });
        editPanel.add(editPatchIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 9, 171, -1));

        editEnterBtn.setFont(new java.awt.Font("Krungthep", 0, 12)); // NOI18N
        editEnterBtn.setText("enter");
        editEnterBtn.setBorderPainted(false);
        editEnterBtn.setOpaque(true);
        editEnterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEnterBtnActionPerformed(evt);
            }
        });
        editPanel.add(editEnterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 9, -1, -1));

        jLabel17.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("TechnicianID:");
        editPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 74, 113, 28));

        editTechnicianIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTechnicianIDFieldActionPerformed(evt);
            }
        });
        editPanel.add(editTechnicianIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 77, 171, -1));

        jLabel18.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Description:");
        editPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 108, 113, 28));

        editDescriptionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDescriptionFieldActionPerformed(evt);
            }
        });
        editPanel.add(editDescriptionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 111, 171, -1));

        patchStatusField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Working", "Not Working" }));
        patchStatusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patchStatusFieldActionPerformed(evt);
            }
        });
        editPanel.add(patchStatusField, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 144, 171, -1));

        jLabel19.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("SoftwareID:");
        editPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 28));

        editPatchTypeComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Application", "System", "Programming", "Network", "Server" }));
        editPatchTypeComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPatchTypeComboBox1ActionPerformed(evt);
            }
        });
        editPanel.add(editPatchTypeComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 171, -1));

        mainPanel.add(editPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 830, -1));

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Select Action");
        mainPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 338, 118, 28));

        jButton1.setText("View All");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        mainPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        ActivateBtn.setText("Activate");
        ActivateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActivateBtnActionPerformed(evt);
            }
        });
        mainPanel.add(ActivateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        MenuTechnicianFrame menuTechnician = new MenuTechnicianFrame();
        menuTechnician.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
        String patchID = searchIDField.getText();
        
        // if there's no testerID inputted, it just prompts again
        if (patchID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter a tester ID to search");
        }
        
        else {
            // a failsafe action just in case
            DefaultTableModel model = Patch.displayRecord(patchID);
            jTable1.setModel(model);
        }
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void actionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionComboBoxActionPerformed
        // TODO add your handling code here:
        String selectedAction = (String) actionComboBox.getSelectedItem();

        if ("Edit".equals(selectedAction)) {
            editPanel.setVisible(true);
            deletePanel.setVisible(false);

        } else {
            deletePanel.setVisible(true);
            editPanel.setVisible(false);
        }
        
        mainPanel.revalidate();
        mainPanel.repaint();

    }//GEN-LAST:event_actionComboBoxActionPerformed

    private void editPatchNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPatchNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPatchNameFieldActionPerformed

    private void editSoftwareIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSoftwareIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editSoftwareIDFieldActionPerformed

    private void editConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editConfirmBtnActionPerformed
        String patchID = editPatchIDField.getText();
        String technicianID = editTechnicianIDField.getText();
        String softwareID = editSoftwareIDField.getText();
        String machineID = editMachineIDField.getText();
        String description = editDescriptionField.getText();
        String patchName = editPatchNameField.getText();
        String patchStatus = (String) patchStatusField.getSelectedItem();
        String patchType = (String) editPatchTypeComboBox1.getSelectedItem();

        String result = Patch.editPatch(patchID, technicianID, softwareID, machineID, description, patchName, patchStatus, patchType);

        switch (result) {
            case "Success":
                JOptionPane.showMessageDialog(this, "Patch info updated successfully!", "Edited Patch", JOptionPane.INFORMATION_MESSAGE);
                // Clear fields
                editPatchIDField.setText("");
                editTechnicianIDField.setText("");
                editSoftwareIDField.setText("");
                editMachineIDField.setText("");
                editDescriptionField.setText("");
                editPatchNameField.setText("");
                patchStatusField.setSelectedIndex(0);
                editPatchTypeComboBox1.setSelectedIndex(0);
                break;
            case "Empty":
                JOptionPane.showMessageDialog(this, "Please fill in all the fields", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case "Not Found":
                JOptionPane.showMessageDialog(this, "Patch ID not found", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case "Invalid Type":
                JOptionPane.showMessageDialog(this, "Invalid patch type selected", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case "Invalid Status":
                JOptionPane.showMessageDialog(this, "Invalid patch status selected", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case "Update Failed":
                JOptionPane.showMessageDialog(this, "Database update did not affect any row", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case "Invalid":
                JOptionPane.showMessageDialog(this, "Database error while updating patch", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case "Cannot change status from Inactive to Working/Not Working":
                JOptionPane.showMessageDialog(this, "Cannot change patch status from Inactive. It needs to be activated first.", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Unknown error", "Error", JOptionPane.ERROR_MESSAGE);
                break;
        }
    }//GEN-LAST:event_editConfirmBtnActionPerformed

    private void addUsernameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUsernameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addUsernameField1ActionPerformed

    private void addPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPasswordField1ActionPerformed

    private void addEmailField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmailField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addEmailField1ActionPerformed

    private void addtesterBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtesterBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addtesterBtn1ActionPerformed

    private void deletePatchIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePatchIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletePatchIDFieldActionPerformed

    private void deletePatchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePatchBtnActionPerformed
        // TODO add your handling code here:
        String patchID = deletePatchIDField.getText();
        
        if (patchID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter a tester ID to delete");
        }
        else {
            try {
                // Need to code Tester Model Class to complete
                String success = Patch.deletePatch(patchID);
                
                if (success.equals("Valid")) {
                    JOptionPane.showMessageDialog(this, "Tester Deleted");
                }
                else {
                    JOptionPane.showMessageDialog(this, "Tester not found.");
                }
            }
            catch (Exception Ex) {
                System.out.println("Error: " + Ex.getMessage());
            }
        }
    }//GEN-LAST:event_deletePatchBtnActionPerformed

    private void editMachineIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMachineIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editMachineIDFieldActionPerformed

    private void editPatchIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPatchIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPatchIDFieldActionPerformed

    private void editEnterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEnterBtnActionPerformed
        String patchID = editPatchIDField.getText().trim();

    if (patchID.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter Patch ID");
        return;
    }

    Patch patch = Patch.getPatchByID(patchID); // Make sure this method returns null if not found

    if (patch != null) {
        // Populate text fields
        editTechnicianIDField.setText(patch.getTechnicianID() != null ? patch.getTechnicianID() : "");
        editMachineIDField.setText(patch.getMachineID() != null ? patch.getMachineID() : "");
        editDescriptionField.setText(patch.getDescription() != null ? patch.getDescription() : "");
        editPatchNameField.setText(patch.getPatchName() != null ? patch.getPatchName() : "");
        editSoftwareIDField.setText(patch.getSoftwareID() != null ? patch.getSoftwareID() : "");

        // Populate Status ComboBox safely
        String status = patch.getStatus() != null ? patch.getStatus().trim() : "";
        boolean statusSet = false;
        for (int i = 0; i < patchStatusField.getItemCount(); i++) {
            if (patchStatusField.getItemAt(i).equalsIgnoreCase(status)) {
                patchStatusField.setSelectedIndex(i);
                statusSet = true;
                break;
            }
        }
        if (!statusSet && patchStatusField.getItemCount() > 0) {
            patchStatusField.setSelectedIndex(0);
        }

        // Populate Type ComboBox safely
        String type = patch.getType() != null ? patch.getType().trim() : "";
        boolean typeSet = false;
        for (int i = 0; i < editPatchTypeComboBox1.getItemCount(); i++) {
            if (editPatchTypeComboBox1.getItemAt(i).equalsIgnoreCase(type)) {
                editPatchTypeComboBox1.setSelectedIndex(i);
                typeSet = true;
                break;
            }
        }
        if (!typeSet && editPatchTypeComboBox1.getItemCount() > 0) {
            editPatchTypeComboBox1.setSelectedIndex(0);
        }

        // Enable fields and confirm button
        editTechnicianIDField.setEnabled(true);
        editMachineIDField.setEnabled(true);
        editDescriptionField.setEnabled(true);
        editPatchNameField.setEnabled(true);
        editSoftwareIDField.setEnabled(true);
        patchStatusField.setEnabled(true);
        editPatchTypeComboBox1.setEnabled(true);
        editConfirmBtn.setEnabled(true);

    } else {
        JOptionPane.showMessageDialog(this, "Patch ID not found", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_editEnterBtnActionPerformed

    private void editTechnicianIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTechnicianIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editTechnicianIDFieldActionPerformed

    private void editDescriptionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDescriptionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editDescriptionFieldActionPerformed

    private void patchStatusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patchStatusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patchStatusFieldActionPerformed

    private void editPatchTypeComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPatchTypeComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPatchTypeComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String patchID = searchIDField.getText();

        DefaultTableModel model = Patch.displayTable();
        jTable1.setModel(model);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ActivateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActivateBtnActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String patchID = editPatchIDField.getText();
        String result = Patch.activate(patchID);

        if (result.equals("Valid")) {
            JOptionPane.showMessageDialog(this, "Patch activated successfully!", "Activated Tester", JOptionPane.INFORMATION_MESSAGE);
        } else if (result.equals("Empty")) {
            JOptionPane.showMessageDialog(this, "Please fill in the information", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (result.equals("Missing")) {
            JOptionPane.showMessageDialog(this, "Patch does not exist", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (result.equals("Invalid")) {
            JOptionPane.showMessageDialog(this, "Invalid information", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (result.equals("Already Active")) {
            JOptionPane.showMessageDialog(this, "Patch is already activated", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ActivateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RecordsPatchFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActivateBtn;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JComboBox<String> actionComboBox;
    private javax.swing.JTextField addEmailField1;
    private javax.swing.JTextField addPasswordField1;
    private javax.swing.JTextField addUsernameField1;
    private javax.swing.JButton addtesterBtn1;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JButton deletePatchBtn;
    private javax.swing.JTextField deletePatchIDField;
    private javax.swing.JButton editConfirmBtn;
    private javax.swing.JTextField editDescriptionField;
    private javax.swing.JButton editEnterBtn;
    private javax.swing.JTextField editMachineIDField;
    private javax.swing.JPanel editPanel;
    private javax.swing.JTextField editPatchIDField;
    private javax.swing.JTextField editPatchNameField;
    private javax.swing.JComboBox<String> editPatchTypeComboBox1;
    private javax.swing.JTextField editSoftwareIDField;
    private javax.swing.JTextField editTechnicianIDField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JComboBox<String> patchStatusField;
    private javax.swing.JPanel plainPanel;
    private javax.swing.JLabel resultsLbl;
    private javax.swing.JTextField searchIDField;
    // End of variables declaration//GEN-END:variables
}
