/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Feedback;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author marcquizon
 */
public class RecordsFeedbackFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RecordsFeedbackFrame.class.getName());

    /**
     * Creates new form AdminMenuFrame
     */
    public RecordsFeedbackFrame() {
        initComponents();
        this.setResizable(false);
        editPanel.setVisible(false);
        deletePanel.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plainPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        addUsernameField1 = new javax.swing.JTextField();
        addPasswordField1 = new javax.swing.JTextField();
        addEmailField1 = new javax.swing.JTextField();
        addtesterBtn1 = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        resultsLbl = new javax.swing.JLabel();
        searchIDField = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        actionComboBox = new javax.swing.JComboBox<>();
        deletePanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        deleteFeedbackIDField = new javax.swing.JTextField();
        deleteFeedbackBtn = new javax.swing.JButton();
        editPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        editDescriptionField = new javax.swing.JTextField();
        editConfirmBtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        editFeedbackIDField = new javax.swing.JTextField();
        editEnterBtn = new javax.swing.JButton();
        editRatingSlider = new javax.swing.JSlider();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        plainPanel.setBackground(new java.awt.Color(40, 48, 143));

        jLabel11.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Username:");

        jLabel12.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Password:");

        jLabel13.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Email:");

        addUsernameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUsernameField1ActionPerformed(evt);
            }
        });

        addPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPasswordField1ActionPerformed(evt);
            }
        });

        addEmailField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmailField1ActionPerformed(evt);
            }
        });

        addtesterBtn1.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        addtesterBtn1.setText("Add Tester");
        addtesterBtn1.setBorderPainted(false);
        addtesterBtn1.setOpaque(true);
        addtesterBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtesterBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plainPanelLayout = new javax.swing.GroupLayout(plainPanel);
        plainPanel.setLayout(plainPanelLayout);
        plainPanelLayout.setHorizontalGroup(
            plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plainPanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addUsernameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(plainPanelLayout.createSequentialGroup()
                        .addGroup(plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addEmailField1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(addtesterBtn1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        plainPanelLayout.setVerticalGroup(
            plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plainPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUsernameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(plainPanelLayout.createSequentialGroup()
                        .addGroup(plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addEmailField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(plainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(plainPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(addtesterBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(40, 48, 143));
        mainPanel.setPreferredSize(new java.awt.Dimension(849, 600));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/SmallLogo.png"))); // NOI18N
        mainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        jLabel2.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Feedback Records");
        mainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 0, 199, 85));

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Click \"Send Feedback on Patch\" on Menu to add a Feedback Record");
        mainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 480, 28));

        backBtn.setBackground(new java.awt.Color(255, 255, 204));
        backBtn.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        backBtn.setText("back");
        backBtn.setBorderPainted(false);
        backBtn.setOpaque(true);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        mainPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 576, 105, 21));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 366, 838, 10));

        resultsLbl.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        resultsLbl.setForeground(new java.awt.Color(255, 255, 255));
        resultsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultsLbl.setText("Results found");
        mainPanel.add(resultsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 62, 178, 28));
        mainPanel.add(searchIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 31, 178, -1));

        SearchBtn.setFont(new java.awt.Font("Krungthep", 0, 14)); // NOI18N
        SearchBtn.setText("Search");
        SearchBtn.setBorderPainted(false);
        SearchBtn.setOpaque(true);
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        mainPanel.add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 31, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 96, 838, 236));

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Search ID:");
        mainPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 28, 88, 28));

        actionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Edit", "Delete" }));
        actionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionComboBoxActionPerformed(evt);
            }
        });
        mainPanel.add(actionComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 338, 110, 26));

        deletePanel.setBackground(new java.awt.Color(40, 48, 143));

        jLabel14.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("FeedbackID:");

        deleteFeedbackIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFeedbackIDFieldActionPerformed(evt);
            }
        });

        deleteFeedbackBtn.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        deleteFeedbackBtn.setText("Delete Feedback");
        deleteFeedbackBtn.setBorderPainted(false);
        deleteFeedbackBtn.setOpaque(true);
        deleteFeedbackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFeedbackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deletePanelLayout = new javax.swing.GroupLayout(deletePanel);
        deletePanel.setLayout(deletePanelLayout);
        deletePanelLayout.setHorizontalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteFeedbackIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(deletePanelLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(deleteFeedbackBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deletePanelLayout.setVerticalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteFeedbackIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(deleteFeedbackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        mainPanel.add(deletePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 830, -1));

        editPanel.setBackground(new java.awt.Color(40, 48, 143));

        jLabel8.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Description:");

        jLabel10.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Overall Rating:");

        editDescriptionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDescriptionFieldActionPerformed(evt);
            }
        });

        editConfirmBtn.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        editConfirmBtn.setText("Confirm edits");
        editConfirmBtn.setBorderPainted(false);
        editConfirmBtn.setOpaque(true);
        editConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editConfirmBtnActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("FeedbackID:");

        editFeedbackIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFeedbackIDFieldActionPerformed(evt);
            }
        });

        editEnterBtn.setFont(new java.awt.Font("Krungthep", 0, 12)); // NOI18N
        editEnterBtn.setText("enter");
        editEnterBtn.setBorderPainted(false);
        editEnterBtn.setOpaque(true);
        editEnterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEnterBtnActionPerformed(evt);
            }
        });

        editRatingSlider.setForeground(new java.awt.Color(255, 255, 255));
        editRatingSlider.setMajorTickSpacing(1);
        editRatingSlider.setMaximum(10);
        editRatingSlider.setPaintLabels(true);
        editRatingSlider.setPaintTicks(true);
        editRatingSlider.setSnapToTicks(true);

        jLabel19.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Low performance");

        jLabel9.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("High performance");

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editDescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(editRatingSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanelLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9)))
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addComponent(editFeedbackIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editEnterBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(206, 206, 206)
                .addComponent(editConfirmBtn)
                .addGap(0, 31, Short.MAX_VALUE))
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editFeedbackIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editEnterBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editDescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(editPanelLayout.createSequentialGroup()
                                .addComponent(editRatingSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanelLayout.createSequentialGroup()
                        .addComponent(editConfirmBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26))))
        );

        mainPanel.add(editPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 830, -1));

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Select Action");
        mainPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 338, 118, 28));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        MenuTesterFrame menuTester = new MenuTesterFrame();
        menuTester.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
        // Read search ID (can be partial or full depending on model)
        String searchID = searchIDField.getText().trim();

        // Use the model's searchFeedback method which returns ArrayList<String[]>
        // Each row expected as: { feedbackID, testerID, patchID, description, rating }
        ArrayList<String[]> matches = Feedback.searchFeedback(searchID);

        // Update label
        resultsLbl.setText(matches.size() + " results found");

        // Build table model: match columns to the searchFeedback return order
        String[] cols = {"Feedback ID", "Tester ID", "Patch ID", "Description", "Rating"};
        javax.swing.table.DefaultTableModel tbl = new javax.swing.table.DefaultTableModel(cols, 0);

        for (String[] row : matches) {
            // Defensive: ensure row has expected length
            if (row.length >= 5) {
                tbl.addRow(new Object[]{
                    row[0], // feedbackID
                    row[1], // testerID
                    row[2], // patchID
                    row[3], // description
                    row[4] // rating
                });
            } else {
                // If shape differs, still try to add what exists
                tbl.addRow(row);
            }
        }

        jTable1.setModel(tbl);
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void actionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionComboBoxActionPerformed
        // TODO add your handling code here:
        String selectedAction = (String) actionComboBox.getSelectedItem();

        if ("Edit".equals(selectedAction)) {
            editPanel.setVisible(true);
            deletePanel.setVisible(false);
        } else { // Delete
            deletePanel.setVisible(true);
            editPanel.setVisible(false);
        }

        mainPanel.revalidate();
        mainPanel.repaint();
    }//GEN-LAST:event_actionComboBoxActionPerformed

    private void editDescriptionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDescriptionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editDescriptionFieldActionPerformed

    private void editConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editConfirmBtnActionPerformed
        // TODO add your handling code here:
        // Gather inputs
        String feedbackID = editFeedbackIDField.getText().trim();
        String newDescription = editDescriptionField.getText().trim();
        int newRating = editRatingSlider.getValue();

        // Call model
        String result = Feedback.edit(feedbackID, newDescription, newRating);

        // Mirror TechnicianFrame style: check return codes and show user-friendly messages
        if (result == "Valid") {
            // Clear fields
            editFeedbackIDField.setText("");
            editDescriptionField.setText("");
            editRatingSlider.setValue(1);

            JOptionPane.showMessageDialog(this, "Feedback edited successfully!", "Edited Feedback", JOptionPane.INFORMATION_MESSAGE);
        } else if (result == "Empty") {
            JOptionPane.showMessageDialog(this, "Please fill in the information", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (result == "Invalid Rating") {
            JOptionPane.showMessageDialog(this, "Rating must be between 1 and 10", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (result == "Missing") {
            JOptionPane.showMessageDialog(this, "Feedback does not exist", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (result == "Patch Not Done") {
            JOptionPane.showMessageDialog(this, "Associated patch has not completed maintenance (cannot edit).", "Error", JOptionPane.ERROR_MESSAGE);
        } else { // covers "Invalid" and any unexpected
            JOptionPane.showMessageDialog(this, "Invalid operation", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editConfirmBtnActionPerformed

    private void addUsernameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUsernameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addUsernameField1ActionPerformed

    private void addPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPasswordField1ActionPerformed

    private void addEmailField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmailField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addEmailField1ActionPerformed

    private void addtesterBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtesterBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addtesterBtn1ActionPerformed

    private void deleteFeedbackIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFeedbackIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteFeedbackIDFieldActionPerformed

    private void deleteFeedbackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFeedbackBtnActionPerformed
        // TODO add your handling code here:
        String feedbackID = deleteFeedbackIDField.getText().trim();

        // Call delete
        String result = Feedback.delete(feedbackID);

        // Mirror TechnicianFrame delete handling
        if (result == "Valid") {
            // Clear field(s)
            deleteFeedbackIDField.setText("");
            JOptionPane.showMessageDialog(this, "Feedback deleted successfully!", "Deleted Feedback", JOptionPane.INFORMATION_MESSAGE);
        } else if (result == "Empty") {
            JOptionPane.showMessageDialog(this, "Please fill in the information", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (result == "Missing") {
            JOptionPane.showMessageDialog(this, "Feedback does not exist", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid operation", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteFeedbackBtnActionPerformed

    private void editFeedbackIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFeedbackIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editFeedbackIDFieldActionPerformed

    private void editEnterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEnterBtnActionPerformed
        // TODO add your handling code here:
        String feedbackID = editFeedbackIDField.getText().trim();

        if (feedbackID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Feedback ID", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Use the model's getInfo (keeps consistency with Technician.getInfo)
        Feedback fb = Feedback.getInfo(feedbackID);

        // Depending on your model, getInfo returns an empty Feedback with null fields if not found.
        // Check the feedbackID field (like Technician frame does).
        if (fb.getFeedbackID() != null) {
            editDescriptionField.setText(fb.getDescription());
            editRatingSlider.setValue(fb.getRating());
        } else {
            JOptionPane.showMessageDialog(this, "Feedback ID not found", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editEnterBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RecordsFeedbackFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchBtn;
    private javax.swing.JComboBox<String> actionComboBox;
    private javax.swing.JTextField addEmailField1;
    private javax.swing.JTextField addPasswordField1;
    private javax.swing.JTextField addUsernameField1;
    private javax.swing.JButton addtesterBtn1;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteFeedbackBtn;
    private javax.swing.JTextField deleteFeedbackIDField;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JButton editConfirmBtn;
    private javax.swing.JTextField editDescriptionField;
    private javax.swing.JButton editEnterBtn;
    private javax.swing.JTextField editFeedbackIDField;
    private javax.swing.JPanel editPanel;
    private javax.swing.JSlider editRatingSlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel plainPanel;
    private javax.swing.JLabel resultsLbl;
    private javax.swing.JTextField searchIDField;
    // End of variables declaration//GEN-END:variables
}
