/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JLayeredPane;
import Controller.*;
import Model.Technician;
import javax.swing.JOptionPane;

/**
 *
 * @author marcquizon
 */
public class RecordsTechnicianFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RecordsTechnicianFrame.class.getName());

    /**
     * Creates new form AdminMenuFrame
     */
    public RecordsTechnicianFrame() {
        initComponents();
        this.setResizable(false);
        addPanel.setVisible(false);
        editPanel.setVisible(false);
        deletePanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        resultsLbl = new javax.swing.JLabel();
        searchIDField = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        actionComboBox = new javax.swing.JComboBox<>();
        deletePanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        deleteTechnicianIDField = new javax.swing.JTextField();
        deleteTechnicianBtn = new javax.swing.JButton();
        addPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        emailSuffixLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addFirstNameField = new javax.swing.JTextField();
        addEmailField = new javax.swing.JTextField();
        addLastNameField = new javax.swing.JTextField();
        addTechnicianBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        addPasswordField = new javax.swing.JTextField();
        addTechnicianPositionComboBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        editPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        editFirstNameField = new javax.swing.JTextField();
        editEmailField = new javax.swing.JTextField();
        editLastNameField = new javax.swing.JTextField();
        editConfirmBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        oldPasswordField = new javax.swing.JTextField();
        editTechnicianPositionComboBox = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        editPasswordField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        editTechnicianIDField = new javax.swing.JTextField();
        editEnterBtn = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        emailSuffixLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(40, 48, 143));
        mainPanel.setPreferredSize(new java.awt.Dimension(849, 599));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/SmallLogo.png"))); // NOI18N
        mainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        jLabel2.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("TECHNICIAN RECORDS");
        mainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1304, 0, 199, 85));

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Select Action");
        mainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 118, 28));

        backBtn.setBackground(new java.awt.Color(255, 255, 204));
        backBtn.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        backBtn.setText("back");
        backBtn.setBorderPainted(false);
        backBtn.setOpaque(true);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        mainPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 568, 105, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 374, 1491, 10));

        resultsLbl.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        resultsLbl.setForeground(new java.awt.Color(255, 255, 255));
        resultsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultsLbl.setText("Results found");
        mainPanel.add(resultsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 62, 178, 28));
        mainPanel.add(searchIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 31, 178, -1));

        SearchBtn.setFont(new java.awt.Font("Krungthep", 0, 14)); // NOI18N
        SearchBtn.setText("Search");
        SearchBtn.setBorderPainted(false);
        SearchBtn.setOpaque(true);
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        mainPanel.add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 31, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 830, 236));

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Search ID:");
        mainPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 28, 88, 28));

        actionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add", "Edit", "Delete" }));
        actionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionComboBoxActionPerformed(evt);
            }
        });
        mainPanel.add(actionComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 110, -1));

        deletePanel.setBackground(new java.awt.Color(40, 48, 143));

        jLabel14.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("TechnicianID:");

        deleteTechnicianIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTechnicianIDFieldActionPerformed(evt);
            }
        });

        deleteTechnicianBtn.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        deleteTechnicianBtn.setText("Delete Technician");
        deleteTechnicianBtn.setBorderPainted(false);
        deleteTechnicianBtn.setOpaque(true);
        deleteTechnicianBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTechnicianBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deletePanelLayout = new javax.swing.GroupLayout(deletePanel);
        deletePanel.setLayout(deletePanelLayout);
        deletePanelLayout.setHorizontalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteTechnicianIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(deletePanelLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(deleteTechnicianBtn)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        deletePanelLayout.setVerticalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteTechnicianIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(deleteTechnicianBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(deletePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 660, 130));

        addPanel.setBackground(new java.awt.Color(40, 48, 143));

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("First Name:");

        emailSuffixLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        emailSuffixLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailSuffixLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        emailSuffixLabel.setText("@ptrackerdb.com");

        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Last Name:");

        addFirstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFirstNameFieldActionPerformed(evt);
            }
        });

        addEmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmailFieldActionPerformed(evt);
            }
        });

        addLastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLastNameFieldActionPerformed(evt);
            }
        });

        addTechnicianBtn.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        addTechnicianBtn.setText("Add Technician");
        addTechnicianBtn.setBorderPainted(false);
        addTechnicianBtn.setOpaque(true);
        addTechnicianBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTechnicianBtnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Password:");

        addPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPasswordFieldActionPerformed(evt);
            }
        });

        addTechnicianPositionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desktop Support", "Network Admin", "System Admin" }));
        addTechnicianPositionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTechnicianPositionComboBoxActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Position:");

        jLabel9.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Email:");

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addFirstNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(addLastNameField))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(addTechnicianPositionComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addPanelLayout.createSequentialGroup()
                                .addComponent(addEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailSuffixLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addComponent(addTechnicianBtn)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailSuffixLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTechnicianPositionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTechnicianBtn))
                .addGap(32, 32, 32))
        );

        mainPanel.add(addPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        editPanel.setBackground(new java.awt.Color(40, 48, 143));

        jLabel13.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("First Name:");

        jLabel15.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Email:");

        jLabel16.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Last Name:");

        editFirstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFirstNameFieldActionPerformed(evt);
            }
        });

        editEmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmailFieldActionPerformed(evt);
            }
        });

        editLastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editLastNameFieldActionPerformed(evt);
            }
        });

        editConfirmBtn.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        editConfirmBtn.setText("Confirm changes");
        editConfirmBtn.setBorderPainted(false);
        editConfirmBtn.setOpaque(true);
        editConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editConfirmBtnActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Leave the password fields blank, to keep it the same");

        oldPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldPasswordFieldActionPerformed(evt);
            }
        });

        editTechnicianPositionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desktop Support", "Network Admin", "System Admin" }));
        editTechnicianPositionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTechnicianPositionComboBoxActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Position:");

        jLabel19.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("New password:");

        editPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPasswordFieldActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("TechnicianID:");

        editTechnicianIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTechnicianIDFieldActionPerformed(evt);
            }
        });

        editEnterBtn.setFont(new java.awt.Font("Krungthep", 0, 12)); // NOI18N
        editEnterBtn.setText("enter");
        editEnterBtn.setBorderPainted(false);
        editEnterBtn.setOpaque(true);
        editEnterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEnterBtnActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Old password:");

        emailSuffixLabel1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        emailSuffixLabel1.setForeground(new java.awt.Color(255, 255, 255));
        emailSuffixLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        emailSuffixLabel1.setText("@ptrackerdb.com");

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(editPanelLayout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(editTechnicianIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(editPanelLayout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(editFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editEmailField)
                            .addComponent(editLastNameField)
                            .addComponent(editTechnicianPositionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(editPanelLayout.createSequentialGroup()
                                .addComponent(editEnterBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17))
                            .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(editPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(oldPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(editPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(editPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(emailSuffixLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(editConfirmBtn)))
                .addGap(18, 18, 18))
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editTechnicianIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editEnterBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oldPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanelLayout.createSequentialGroup()
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailSuffixLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editTechnicianPositionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanelLayout.createSequentialGroup()
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editConfirmBtn)
                        .addGap(17, 17, 17)))
                .addGap(32, 32, 32))
        );

        mainPanel.add(editPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, 170));

        jLabel8.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Technician Records");
        mainPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 0, 199, 85));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 856, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        MenuTechnicianFrame menuTechnician = new MenuTechnicianFrame();
        menuTechnician.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
        String technicianID = searchIDField.getText();

    }//GEN-LAST:event_SearchBtnActionPerformed

    private void actionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionComboBoxActionPerformed
        // TODO add your handling code here:
        String selectedAction = (String) actionComboBox.getSelectedItem();

        if ("Add".equals(selectedAction)) {
            addPanel.setVisible(true);
            editPanel.setVisible(false);
            deletePanel.setVisible(false);

        } else if ("Edit".equals(selectedAction)) {
            addPanel.setVisible(false);
            editPanel.setVisible(true);
            deletePanel.setVisible(false);

        } else {
            deletePanel.setVisible(true);
            addPanel.setVisible(false);
            editPanel.setVisible(false);
        }

    }//GEN-LAST:event_actionComboBoxActionPerformed

    private void deleteTechnicianIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTechnicianIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteTechnicianIDFieldActionPerformed

    private void deleteTechnicianBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTechnicianBtnActionPerformed
        // TODO add your handling code here:
        String technicianID = deleteTechnicianIDField.getText();

        if (Technician.delete(technicianID) == "Valid") {
            deleteTechnicianIDField.setText("");
            JOptionPane.showMessageDialog(this, "Technician deleted successfully!", "Deleted Technician", JOptionPane.INFORMATION_MESSAGE);
        } else if (Technician.delete(technicianID) == "Empty") {
            JOptionPane.showMessageDialog(this, "Please fill in the information", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (Technician.delete(technicianID) == "Missing") {
            JOptionPane.showMessageDialog(this, "Technician does not exist", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (Technician.delete(technicianID) == "Invalid") {
            JOptionPane.showMessageDialog(this, "Invalid information", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteTechnicianBtnActionPerformed

    private void addFirstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFirstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFirstNameFieldActionPerformed

    private void addEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addEmailFieldActionPerformed

    private void addLastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addLastNameFieldActionPerformed

    private void addTechnicianBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTechnicianBtnActionPerformed
        // TODO add your handling code here:
        String firstName = addFirstNameField.getText();
        String lastName = addLastNameField.getText();
        String email = addEmailField.getText();
        String position = (String) addTechnicianPositionComboBox.getSelectedItem();
        String password = addPasswordField.getText();

        if (Technician.add(firstName, lastName, email, position, password) == "Valid") {
            //Makes the textfields blank again
            addFirstNameField.setText("");
            addLastNameField.setText("");
            addEmailField.setText("");
            addTechnicianPositionComboBox.setSelectedItem(1);
            addPasswordField.setText("");

            JOptionPane.showMessageDialog(this, "Technician added successfully!", "Added Technician", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("ADD: Technician " + firstName + " " + lastName + "added");
        } else if (Technician.add(firstName, lastName, email, position, password) == "Empty") {
            //This is an error when the User leaves a certain field blank
            JOptionPane.showMessageDialog(this, "Please fill in the information", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (Technician.add(firstName, lastName, email, position, password) == "Duplicate Email") {
            //This is an error when the User inputs a duplicate email
            JOptionPane.showMessageDialog(this, "Duplicate email found, please change", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addTechnicianBtnActionPerformed

    private void addPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPasswordFieldActionPerformed

    private void addTechnicianPositionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTechnicianPositionComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTechnicianPositionComboBoxActionPerformed

    private void editFirstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFirstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editFirstNameFieldActionPerformed

    private void editEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEmailFieldActionPerformed

    private void editLastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editLastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editLastNameFieldActionPerformed

    private void editConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editConfirmBtnActionPerformed
        // TODO add your handling code here:
        String technicianID = editTechnicianIDField.getText();
        String firstName = editFirstNameField.getText();
        String lastName = editLastNameField.getText();
        String email = editEmailField.getText();
        String position = (String) editTechnicianPositionComboBox.getSelectedItem();
        String currentPassword = oldPasswordField.getText();
        String newPassword = editPasswordField.getText();

        if (Technician.edit(technicianID, firstName, lastName, email, position, currentPassword, newPassword) == "Valid") {
            //Makes the textfields blank again
            editTechnicianIDField.setText("");
            editFirstNameField.setText("");
            editLastNameField.setText("");
            editEmailField.setText("");
            editTechnicianPositionComboBox.setSelectedItem(1);
            oldPasswordField.setText("");
            editPasswordField.setText("");
            
            JOptionPane.showMessageDialog(this, "Technician edited successfully!", "Edited Technician", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("EDIT: Technician " + firstName + " " + lastName + "edited");
        } else if (Technician.edit(technicianID, firstName, lastName, email, position, currentPassword, newPassword) == "Empty") {
            //This is an error when the User leaves a certain field blank
            JOptionPane.showMessageDialog(this, "Please fill in the information", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (Technician.edit(technicianID, firstName, lastName, email, position, currentPassword, newPassword) == "Duplicate Email") {
            //This is an error when the User inputs a duplicate email
            JOptionPane.showMessageDialog(this, "Duplicate email found, please change", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (Technician.edit(technicianID, firstName, lastName, email, position, currentPassword, newPassword) == "Wrong password") {
            //This is an error when the User wanted to change the password, but inputted the wrong old password
            oldPasswordField.setText("");
            JOptionPane.showMessageDialog(this, "Wrong password", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editConfirmBtnActionPerformed

    private void oldPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldPasswordFieldActionPerformed

    private void editTechnicianPositionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTechnicianPositionComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editTechnicianPositionComboBoxActionPerformed

    private void editPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPasswordFieldActionPerformed

    private void editTechnicianIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTechnicianIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editTechnicianIDFieldActionPerformed

    private void editEnterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEnterBtnActionPerformed
        // TODO add your handling code here:
        // This function will fill up the text fields with the current Info depending on the technician ID inputted
        String technicianID = editTechnicianIDField.getText();
        Technician technician = new Technician();
        technician = Technician.getInfo(technicianID);

        if (technician.getTechnicianID() != null) {
            Technician currentInfo = new Technician(); //Initialize a currentInfo Technician variable
            currentInfo = Technician.getInfo(technicianID); //Gets the information from the getInfo function
            editFirstNameField.setText(currentInfo.getFirstName());
            editLastNameField.setText(currentInfo.getLastName());
            editEmailField.setText(currentInfo.getEmail());
            editTechnicianPositionComboBox.setSelectedItem(currentInfo.getPosition());
            System.out.println("EDIT: Technician ID " + currentInfo.getTechnicianID() + " current info retrieved");
        } else {
            JOptionPane.showMessageDialog(this, "Technician ID not found", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("EDIT: Technician ID " + technicianID + " does not exist");

        }

    }//GEN-LAST:event_editEnterBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RecordsTechnicianFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchBtn;
    private javax.swing.JComboBox<String> actionComboBox;
    private javax.swing.JTextField addEmailField;
    private javax.swing.JTextField addFirstNameField;
    private javax.swing.JTextField addLastNameField;
    private javax.swing.JPanel addPanel;
    private javax.swing.JTextField addPasswordField;
    private javax.swing.JButton addTechnicianBtn;
    private javax.swing.JComboBox<String> addTechnicianPositionComboBox;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JButton deleteTechnicianBtn;
    private javax.swing.JTextField deleteTechnicianIDField;
    private javax.swing.JButton editConfirmBtn;
    private javax.swing.JTextField editEmailField;
    private javax.swing.JButton editEnterBtn;
    private javax.swing.JTextField editFirstNameField;
    private javax.swing.JTextField editLastNameField;
    private javax.swing.JPanel editPanel;
    private javax.swing.JTextField editPasswordField;
    private javax.swing.JTextField editTechnicianIDField;
    private javax.swing.JComboBox<String> editTechnicianPositionComboBox;
    private javax.swing.JLabel emailSuffixLabel;
    private javax.swing.JLabel emailSuffixLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField oldPasswordField;
    private javax.swing.JLabel resultsLbl;
    private javax.swing.JTextField searchIDField;
    // End of variables declaration//GEN-END:variables
}
